services:
  iepg-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iepg-server
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=40870
      - LOG_LEVEL=debug
      - DB_PATH=/app/data/programs.db
      - MIRAKURUN_URL=http://localhost:40772/api
      - RECREATE_DB=true  # 起動のたびにデータベースを再作成
